.circleci/config.yml, README.md
Dette pull request tilhører issue #163. Det er konfiguration mht. afvikling af tests i circle ci.
=> Circle CI configuration

.circleci/config.yml, .coveragerc, .flake8, forenings_medlemmer/settings_test.py
Har tilføjet lidt bedre oversigt til #163. Tests spytter nu JUNIT reports ud i xml format som circleci kan præsentere.
=> added test summary to circleci

members/views/waitinglistView.py
There was a problem with people not being able to see the waiting list if they aren't logged in, this is now fixed.
=> Fix waitinglist

members/static/members/css/login.css, members/templates/members/base.html, members/templates/members/login.html
Opdatering af layoutet på log ind siden.
=> Updated login page layout

.env.example
=> Fixed error in .env.example

.github/workflows/prepare-deploy.yml
Jeg havde givet miljøvariablen det forkerte navn
=> Fixes coverage

members/templates/members/forgot.html
#386 
Not sure what i'd do to make it prettier otherwise, as visual design isn't really my strong suit
=> Centered the reset password form

members/static/members/sass/base.scss, members/static/members/sass/base_layout.scss, members/static/members/sass/entry_page.scss, members/static/members/sass/header.scss, members/templates/members/base.html
Fixer header text, størrelse og breakpoints
=> Styling update

members/static/members/sass/footer.scss, members/templates/members/base.html
=> Fixed footer size

poetry.lock
=> Updated lock file

members/templates/members/activities.html, members/tests/test_model_department.py
=> reversed the buttons so it fits

.github/workflows/test.yml, members/models/quickpaytransaction.py, members/tests/test_functional/functional_helpers.py, members/tests/test_functional/test_payment_status.py, poetry.lock, pyproject.toml
* Fixer payment bug
* Test af at det virker
* Updaterer pakker
=> Payment fix

codecov.yaml, members/admin/department_admin.py, members/forms/admin_signup_form.py, members/forms/person_form.py, members/forms/signup_form.py, members/forms/volunteer_signup_form.py, members/migrations/0004_auto_20191225_1237.py, members/migrations/0013_remove_department_has_waiting_list.py, members/migrations/0014_auto_20200103_2141.py, members/migrations/0018_auto_20200130_1731.py, members/migrations/0019_auto_20200203_1322.py, members/migrations/0019_remove_union_region.py, members/migrations/0021_auto_20200309_1107.py, members/models/department.py, members/models/family.py, members/models/payment.py, members/models/statistics/old_stat_code.py, members/tests/factories/providers.py, members/tests/test_for_uncreated_migrations.py, members/tests/test_model_address.py, poetry.lock, pyproject.toml
- Updated black to new version
- Ran updated black on code
=> black update

members/management/commands/create_membership_activitys.py
Temporary fix. Let's get it fixed permanently soon
=> New membership activites 2021

members/templates/members/entry_page.html
Ændrer overskrift, så den giver mening.
=> Opdatering overskrift i entry_page

members/admin/__init__.py
issue fixed, prefix for note changed from self to p
=> Fix issue with export af deltagere list

members/models/activityparticipant.py
to include that payment is accepted (and not confirmed, and start year is in future)
=> Changed condition for check for payment in future

.env.example, docker-compose.yml
Makes the docker-compose.yml files compatible with the docker alternative podman
=> Make docker-compose.yml compatible with podman

members/models/family.py, members/models/waitinglist.py, members/templates/members/activities.html, members/templates/members/activity_signup.html, members/views/Activities.py, members/views/ActivitySignup.py
=> bug/810-Non-childs could not use "Tilmeld"

members/views/Activities.py
Testet her lokalt før og efter, og problemet er nu løst
=> Rettet fra Child to Person.

members/admin/activity_admin.py
Reverts CodingPirates/forenings_medlemmer#839
Fejler når man vælger en forening eller afdeling på https://medlemssystem-staging.herokuapp.com/admin/members/activity/
=> Revert "Vis kun foreninger og afdelinger i dropdown for aktivitet admin siden, som brugeren har adgang til"

members/admin/activityparticipant_admin.py, members/admin/person_admin.py
Export failed w eror 500 if a person did not have a defined gender.
Gender is mandatory, but there are a few persons without gender.
This change will map unknown (null) to "andet", and also change Edit of person in Admin to show Gender field
=> Default value for unknown gender, and gender as field in admin>Person

members/tests/test_functional/test_admin_can_load.py
=> Add argument disable-dev-shm-usage for chrome in selenium test

members/admin/activityparticipant_admin.py
Filter for forening var baseret på foreningen på aktiviteten (der kun bruges til medlemskab) - rettet til at være forening for den afdeling der er på aktiviteten
Filtre for forening og afdeling er nu sorteret efter navn
=> Rettet fejl foreningsfilter, samt lavet sortering af forening+afd

members/admin/union_admin.py
Forenings navn, oprettelses og evt lukke dato
Formand, Næstformand, Kasserer og Sekretær: Navn, email og telefon
=> Eksporter informationer om foreninger

members/forms/admin_signup_form.py, members/forms/person_form.py, members/forms/volunteer_signup_form.py
Datoformat er afhængig af regional settings, og date-picker viser det rigtigt
=> Fjernede dato format (dd-mm-åååå) i labels

members/templates/members/membership.html
https://members.codingpirates.dk/membership/
=> Sortering af foreningsmedlemskaber

members/admin/union_admin.py
Listen af board members var ikke sorteret (eller måske sorteret efter pk for personer)
=> Sortering af board_members for forening

members/admin/department_admin.py, members/admin/union_admin.py
Kolonnen viser nu antal på venteliste for den given afdeling/forening samt et link til Venteliste, med filter for den givne afdeling/forening
=> Admin: Ny  kolonne for Afdelinger og Foreninger med venteliste

members/admin/admin_actions.py
Manglede på #956 (Send email for invitationer, nu også med ekstra tekst)
=> Tilføje template til invitation mail context

members/admin/user_admin.py
Desuden ændrede date_joined , last_login og username til at være readonly
=> Fjernede mulighed for at ændre rettigheder for normal admin

members/admin/admin_actions.py, members/tests/test_admin_admin_actions.py
Reverts CodingPirates/forenings_medlemmer#996
Tager ikke højde for situation hvor person ikke opfylder alderskrav dags dato, men bliver gammel nok til aktivitets start. Dette skal der skal skrives test for
=> Revert "[#975] Check for alder på dags dato om person kan inviteres til aktivitet"

members/admin/activity_admin.py
Vi fik fejlkode 500 på staging, når man forsøgte at oprette ny aktivitet
=> Kan ikke generere link til aktivitet der er ved at blive oprettet

members/admin/waitinglist_admin.py
Desuden ændrede kolonneoverskrift fra "Nummer på venteliste" til "Ventelistenummer"
=> Admin > Venteliste: Tilføjede Postnummer og Kommune til ventelisteoversigt

members/admin/department_admin.py
Fjernede også ID kolonne (den havde link til det samme som Afdelingskolonne)
=> Admin > Afdeling: Flyt Foreningskolonne, og sorter på Venteliste antal

members/tests/test_functional/test_account_login.py, members/tests/test_functional/test_entry_page.py
2 of the 4 reported .PNG files changed now.
The 2 other files were already changed.
=> Changed name of 2 files made by tests

members/admin/activity_admin.py
start_date DESC
department__name ASC
name ASC
=> Admin > Aktiviteter:  Default sortering

members/admin/waitinglist_admin.py, members/tests/test_functional/test_admin_waitinglist.py
In Admin > Waitinglist
1. Reference to person__municipality changed to person__municipality__name
2. added filter for municipality
=> Fixed issue with search in Waitinglist and added Municipality filter

members/jobs.py, members/models/person.py
Opfølgning på https://github.com/CodingPirates/forenings_medlemmer/pull/1139, hvor kommune-felt blev lavet om til relation
Tilrettet `person.update_dawa_data()` så den fungerer med nyt kommune-felt, og kør cron-job igen.
Testet lokalt med
```
docker compose -f docker-compose.yml -f docker-compose.arm64.yml run web ./manage.py shell
>>> from members.jobs import UpdateDawaData
>>> UpdateDawaData.do(None)
```
og valideret i database at person blev opdateret korrekt
=> Opdater update_dawa_data() til at bruge nyt kommune-felt
