CodingPirates/forenings_medlemmer

README.md
Issue #163 - Simpel bugfix - README CI link pegede på min version og ikke den nyoprettede til coding pirates.
=> link i readme til ci rettet så det peger på codingpirates og ikke lronhoj ci

.github/workflows/run_tests.yml
Opsætter Github actions som vores test runner, tanken er at vi så kan skifte væk fra Circle CI da github er nemmere at administrere og har et bedre interface.
Se [interface eksempel](https://github.com/CodingPirates/forenings_medlemmer/pull/335/checks?check_run_id=321295303)
=> Config for github actions

members/static/members/sass/base.scss, members/templates/members/activities.html, members/templates/members/family_details.html, members/templates/members/logout.html, members/urls.py
Det ser måske voldsomt ud, men det er det ikke.
Tabs er reguleret
`row` og `col-12` sammen er fjernet
`align=left` fjernet (default)
Log ud-side er oprettet
`blockquote` er blevet til `alert`
`col` er fjernet ved nogle tabeller, hvor det ikke er nødvendigt. Nu kan de istedet automatisk resize
Løser #310 #259
Jeg håber den er ligetil
=> Mundskyld fixdel - oprydning og log ud-side

members/static/members/sass/buttons.css
Fjerner standard border fra knapperne 
Sådan så de ud før
Sådan ser de ud nu
=> Removed border from bootstrap buttons

codecov.yaml
It's annoying to have red check due to minus `0.2` in coverage. 
Now it will only fail if coverage falls by 2%
=> Made codecov more lenient in CI

members/forms/person_form.py
Noticed by @mhewel
Previously the label when editing person birthday was incorrectly `mm-dd-åååå`, whereas the field is actually using `dd-mm-åååå`
From running locally:
=> Change UI label from 'mm-dd-åååå' -> 'dd-mm-åååå'

members/views/EntryPage.py
Fix for the `'NoneType' object has no attribute 'family'` error we have seen after https://github.com/CodingPirates/forenings_medlemmer/pull/436 was deployed couple of weeks ago
Was able to reproduce locally when signed in as admin and going to frontpage
=> Handle authenticated user request without database user

.github/CONTRIBUTING.md, docker-compose.yml, pgadmin4/servers.json
When investigating the `'NoneType' object has no attribute 'family'` error, needed to have easy access to local database for testing.
So decided to add pgAdmin container to Docker Compose setup. After running `docker compose up`, it runs on http://localhost:5050, and gives a graphical interface to local Postgres database:
Hope others can find that useful :)
=> Add pgAdmin to Docker Compose

Dockerfile
We experienced build errors like
```
Step 4/21 : RUN npm install -g npm
---> Running in a67f4bf03f35
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'npm@9.1.2',
npm WARN EBADENGINE   required: { node: '^14.17.0 || ^16.13.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
```
According to https://stackoverflow.com/a/34594609 / https://github.com/nodesource/distributions/blob/master/README.md#debinstall special command is required for installing newer node.js versions on Debian
=> Upgrade to Node.js 14.x

members/admin/__init__.py
Beskrivelse af handling for CSV Export i Admin > Deltagere er rettet til at være uden alle felter angivet i parantes
=> Feature/#761. Beskrivelse af handling for CSV Export i Admin > Deltagere

members/models/emailtemplate.py
Default is still : dont allow duplicate, but for e.g. Delete from Waitinglist can now send emails every time the same person is deleted from waitinglist for a department
=> Tillad multiple emails for konkrete use cases (issue #737)

.github/CONTRIBUTING.md, pre-commit
Since .git is ignored by git by default you have to move the pre-commit file to .git/hooks to enable it. Added tutorial to enable auto formatting in contributing.md
=> Kør 'black' hver gang vi laver noget, så det er nemmere at læse koden

poetry.lock, pyproject.toml
Se f.eks. https://github.com/CodingPirates/forenings_medlemmer/actions/runs/4772419383/jobs/8485607295?pr=872 som fejler med
```
Unable to find installation candidates for codecov (2.1.12)
```
Ifølge https://about.codecov.io/blog/message-regarding-the-pypi-package/ er der ny 2.1.13 pakke tilgængelig nu
=> Opdater codecov til 2.1.13

members/templates/members/department_signup.html
Er på https://members.codingpirates.dk/department_signup, hvor nuværende mailto link er tomt
=> Alle Ventelister: Mailto-link indeholder ikke mail addresse

members/admin/user_admin.py
Rettede logik for forenings og afdelings filtrene.
Tilføjede "ingen" til alle 3 filtre og "mindst en" for forenings- og afdelings filtrene.
=> Rettede filtre for Grupper,  Forening og Afdelinger

members/admin/activityparticipant_admin.py
Tidligere viste `Afdelinger` dropdown på https://members.codingpirates.dk/admin/members/activityparticipant/ alle afdelinger:
Med denne rettelse vises kun relevante afdelinger. Dette er samme kode som brugt i f.eks. https://github.com/CodingPirates/forenings_medlemmer/blob/master/members/admin/waitinglist_admin.py
=> Vis kun relevante afdelinger i dropdown på deltager admin side

members/static/members/js/tab.js, members/templates/members/activities.html, members/views/ActivitySignup.py
Se #846 
Når man har tilmeldt sig aktivitet bliver man ledt videre til oversigt over tilmeldte aktiviteter, da der ellers lader til at være tendens til at forældre skriver sig på venteliste igen.
Dette inkluderer:
* Support for `#` i url til at vælge aktive faneblad/tab, testet lokalt med f.eks. http://localhost:8000/activities/#tab-tilmeldte-aktiviteter - se screendump
* Når man har tilmeldt sig en aktivitet, bliver brugeren viderestillet til `/activities/#tab-tilmeldte-aktiviteter`
=> Når man har tilmeldt sig aktivitet skal man ikke sendes tilbage til venteliste opskrivning

members/admin/activityinvite_admin.py
Efter review fra @lakridserne på #963 (vis checkmark på invitation, om person allerede er tilmeldt aktivitet), ændret `count() > 0` til `exists()`
=> Opdatering til #963: Brug exists() i stedet for count()

members/templates/members/activities.html, members/templates/members/activity_signup.html, members/templates/members/header.html
Se https://github.com/CodingPirates/forenings_medlemmer/issues/762
Brug `next` query string parameter til at redirect'e brugeren tilbage til f.eks. aktivitetsside efter login. Brugen af `next` er dokumenteret på f.eks. https://docs.djangoproject.com/en/4.2/topics/auth/default/#the-login-required-decorator:
> will use the value of `redirect_field_name` as its key rather than "next" (the default).
=> Redirect bruger efter login

members/templates/members/entry_page.html, members/templates/members/user_created.html
Del af [#969 [Feature] Redirect bruger til seneste side, ved brugeroprettelse og flyt information om Piratnyt osv til forsiden](https://github.com/CodingPirates/forenings_medlemmer/issues/969)
Denne boks med links til Piratnyt tilmelding og Facebook er tilføjet forsiden fra siden når man har oprettet sig som bruger (hvor man typisk er i gang med at tilmelde til en aktivitet, så man tænker ikke lige over Piratnyt osv)
=> Flyt links til Piratnyt og Facebook til forsiden, fra user-signup side

members/templates/admin/base_site.html
Relateret til https://codingpirates.slack.com/archives/C2NCFUE30/p1704803609722099, hvor vi skulle sende link til admin guide i Slack. Hvis denne havde været tilgængelig fra admin UI, havde brugeren måske nemmere kunne have fundet informationen selv.
Implementeret ifølge https://docs.djangoproject.com/en/3.2/howto/overriding-templates/#extending-an-overridden-template
**Desktop eksempel:**
**Mobil:**
=> Vis links til frivilligportal guide fra admin UI

members/admin/admin_actions.py, members/tests/test_admin_admin_actions.py
Relateret til [#975 [BUG] Kan ikke invitere personer der er gamle nok](https://github.com/CodingPirates/forenings_medlemmer/issues/975)
Ændre til simpelthen blot at se på alder i forhold til dags dato, om person opfylder alderskrav.
Bemærk der nu udelukkende ses på dags dato, ikke i forhold til aktivitetens startdato. Dvs. der vil være børn som er blevet for gamle i mellemtiden, som ikke længere vil blive inviteret. Men i praksis er dette nok ikke et reelt problem, givet kun få børn bliver så længe
Har derudover rettet test logik en smule til, så det er nemmere at genkende test personer i forbindelse med debugging af test
=> [#975] Check for alder på dags dato om person kan inviteres til aktivitet

members/admin/admin_actions.py, members/tests/test_admin_admin_actions.py
Retter [#975 Kan ikke invitere personer der er gamle nok](https://github.com/CodingPirates/forenings_medlemmer/issues/975)
* Ved alderscheck for "too young", kigges også på dags dato
* TIlføjet test for
* Invitation til aktivitet i fremtiden
* Invitation til aktivitet der er startet (her træder det nye alderscheck i kraft)
* Desuden rettet tests, så der nu bruges relative datoer, og vi ikke har problemer omkring årsskiftet
=> [#975] Check også dags dato for alderscheck ved invitationer

members/templates/members/header.html
Se #1028 
Hvis bruger lige havde logget ud, og ville logge ind igen, blev man viderestillet til logout, og det kunne man så gøre et stykke tid...
Rettelsen er blot ikke at viderestille hvis man trykker på "Log ind" link fra logout siden
=> [#1028] Viderestil ikke url ved login, hvis kommer fra logout side

members/admin/department_admin.py, members/admin/union_admin.py
=> Admin: Siden for en afdeling og siden for en forening har nu liste med admins

.github/CONTRIBUTING.md, .github/workflows/test.yml
Github Actions fejlede med
```
> Run docker-compose build
line 1: docker-compose: command not found
```
F.eks. https://github.com/CodingPirates/forenings_medlemmer/actions/runs/10316590977/job/28559134471?pr=1099
=> 'docker-compose' -> 'docker compose'

.github/workflows/test.yml
Fik fejl i https://github.com/CodingPirates/forenings_medlemmer/actions/runs/10890213124/job/30218456052?pr=1107
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2.1.4`.
Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
=> Updated to actions/upload-artifact@v4.4.0

members/models/activity.py
Løser #1105, tilføjet validering af dato-felter for aktivitet
Testet lokalt
=> Valider at dato-felter for aktivitet er udfyldt

.github/CONTRIBUTING.md, docker-compose.arm64.yml, docker-compose.yml
* Fjernet `version` felt fra `docker-compose.yml`, for at undgå følgende advarsel:
```
WARN[0000] /Users/rasmus/src/github.com/CodingPirates/forenings_medlemmer/docker-compose.yml:
the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```
* Tilføjet Docker Compose fil til brug på Apple M1 (ARM64) maskiner, samt tilføjet beskrivelse til contributing guide. I fald andre kører ARM64
=> Tilføjet Docker Compose fil for ARM64, samt fjernet obsolete version felt

members/admin/admin_actions.py, members/tests/test_admin_admin_actions.py
Dette er ifm siden hvor man skal bekræftige afdeling + aktivitet samt evt skrive mere info til invitation
=> Opdater AdminActions.invite_many_to_activity_action: Vis kun åbne afdelinger

pyproject.toml
Vi oplevede pludselig at [builds fejlede](https://github.com/CodingPirates/forenings_medlemmer/actions/runs/12732354292/job/35487437263) med
```
Error: The current project could not be installed: No file/folder found for package forenings-medlemmer
```
Tilsyneladende har noget ændret sig i Poetry. I hvert fald ifølge https://python-poetry.org/docs/basic-usage/#operating-modes, ser det ud til at eftersom vi ikke bygger en pakke, kan vi sætte `package-mode = false`
=> Sæt package-mode = false i pyproject.toml

members/admin/anonymization_candidates_admin.py
Brug query filter i stedet for at kalde `person.is_anonymization_candidate()` for hver person. Har testet lokalt med 10.000 personer, og er mærkbart hurtigere.
Selve visningen kalder stadig `person.is_anonymization_candidate()` for at vise farven, så man vil se hvis filter skulle have inkluderet en forkert person
=> Optimer visning af "anonymiserings kandidater" liste

members/admin/anonymization_candidates_admin.py, members/models/person.py, members/tests/test_model_person.py
Relateret til #739 - GDPR
Opdateret anonymiserings-logik baseret på snak i dag til udviklingsdag sammen med Stig:
En person kan anonymiseres hvis:
1. Længere end 2 år siden vedkommende har deltaget i aktivitet
1. Længere end 5 år siden en i vedkommendes familie har haft en betaling, hvilket betyder at:
a. en forældre ikke kan anonymiseres hvis der er betalt for et barn indenfor seneste 5 år
b. søskende, der aldrig har gået til Coding Pirates, ikke kan anonymiseres, hvis der er betaling for andre i familien
=> [#739] Anonymisering: 2 år siden seneste aktivitet eller betaling indenfor 5 regnskabsår 
